name: flutter_six_paths_state
description: A Flutter project to compare the most used ways to manage state.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_mobx: ^2.0.1
  flutter_redux: ^0.8.2
  get: ^4.3.4
  mobx: ^2.0.3
  provider: ^5.0.0
  redux: ^5.0.0
  six_paths_core:
    path: packages/six_paths_core

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
